### ISSUE TITLE
Suggest to loosen the dependency on boltons

### ISSUE THREAD

**Issue by Agnes-U** [ckarageorgkaneen/using-asyncio-examples#2]
Hi, your project using-asyncio-examples(commit id: e3257b70a30953cac389820121045b52e289925b) requires "boltons==20.2.1" in its dependency. After analyzing the source code, we found that the following versions of boltons can also be suitable, i.e., boltons 19.0.0, 19.0.1, 19.1.0, 19.2.0, 19.3.0, 20.0.0, 20.1.0, 20.2.0, 21.0.0, since all functions that you directly (1 APIs: boltons.cacheutils.LRU.__init__) or indirectly (propagate to 4 boltons's internal APIs and 1 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on boltons from "boltons==20.2.1" to "boltons>=19.0.0,<=21.0.0". This will improve the applicability of using-asyncio-examples and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on boltons?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by ckaraneen** [comment]
Happy to review any pull request.

**Comment by Agnes-U** [comment]
Thanks, here's the [PR](https://github.com/ckarageorgkaneen/usingaio/pull/3).
